### PR TITLE
FAQ section done

### PR DESCRIPTION
**Pull request by Ayushsahrawat**
I have completed the FAQ section .

### CODE REVIEW

**Review by Dhruv031003 — CHANGES_REQUESTED** [review]
Some changes are needed

**Comment by Dhruv031003** [comment]
@Ayushsahrawat 
There are some issues with you code.
- The buttons are not working properly
- Initially the Answers should be in closed state.
- Add margin from the sides for the outermost container

**Comment by Ayushsahrawat** [comment]
all the issues are fixed for now

**Comment by Dhruv031003** [comment]
@Ayushsahrawat Okay all issues are fixed I am merging this PR

**Pull request merged**
