### PR TITLE
Add functionality in navbar and donate button

### PR DESCRIPTION
**Pull request by Vanshika61**
Hey, I have fixed the given issue, if it is good then merge this pr.

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@Vanshika61 
When Raising a PR or referring to an issue you can link the issue by using "#" and then selecting the issue.
image

**Comment by Dhruv031003** [comment]
The issue you fixed is closed. You closed it?

**Comment by Dhruv031003** [comment]
Functionality of "Donate Now" button is also not added.
- You can link it to the Donate section

**Comment by Dhruv031003** [comment]
@Vanshika61 
The home button needs to be disabled when we are at the top of the page.
This can be done by using Javascript.

**Comment by Vanshika61** [comment]
#30 , 
This is the issue @Dhruv031003 .

**Comment by Dhruv031003** [comment]
@Vanshika61 Yes I saw that

**Comment by Dhruv031003** [comment]
Fix the issues and commit the changes again

**Comment by Vanshika61** [comment]
I have fix the issues you can check it.

**Pull request merged**
