### PR TITLE
Customize scrollbar

### PR DESCRIPTION
**Pull request by AnupeshVerma**

### CODE REVIEW

**Comment by anupeshverma** [comment]
Regarding issue #74

**Comment by Dhruv031003** [comment]
@anupeshverma 
Please match the colors with the rest of the page.
You can get the value of colors from the figma file link present in the Readme.

**Comment by anupeshverma** [comment]
sorry I didn't get that 😐

**Comment by Dhruv031003** [comment]
@anupeshverma 
No issues.
- dark= #094513
- mid= #5F9E69
- light= #BCFCC6

Use these values for the color of the scrolbar.

**Comment by AnupeshVerma** [comment]
Now please review it

**Comment by Dhruv031003** [comment]
@anupeshverma 
Sorry for the late reply and merge I was stuck in some personal problems.

**Pull request merged**
