### PR TITLE
Made Navbar Sticky #31

### PR DESCRIPTION
**Pull request by aryanlath**
I have made the navbar sticky.

### CODE REVIEW

**Comment by mr-palindrome** [comment]
Hey @aryanlath 
Please have a look at the following screenshot. The navbar is sticky til the first div.
image

**Comment by aryanlath** [comment]
Yeah I get it, so do you want it to be sticky till the end of the page rather than its parent?

**Comment by aryanlath** [comment]
Screenshot 2022-10-17 at 1 27 15 AM
Is this what you wanted?

**Comment by mr-palindrome** [comment]
> Screenshot 2022-10-17 at 1 27 15 AM
> Is this what you wanted?

Yeah something like that, but can you change back the color to the old one... Which is also available in the UI

**Comment by aryanlath** [comment]
Yeah sure I will do that

**Comment by aryanlath** [comment]
Screenshot 2022-10-17 at 5 54 00 PM
Is this fine now?

**Comment by mr-palindrome** [comment]
> Screenshot 2022-10-17 at 5 54 00 PM
> 
> Is this fine now?
image


Fix this as well!

**Comment by aryanlath** [comment]
Screenshot 2022-10-18 at 12 03 51 AM
I have corrected this, is there anything else that is needed?

**Comment by aryanlath** [comment]
Is there still any problem with the navbar?

**Comment by Dhruv031003** [comment]
@aryanlath No everthing's fine with it now. Just solve the merge conflicts.

**Pull request closed without merging**
