### PR TITLE
Donate Here Section

### PR DESCRIPTION
**Pull request by Mahak008**
Closing issue #34  #35 
I have made the changes required and have made this section responsive too.

Laptop View:

Screenshot (339)

Mobile View:

Screenshot (341)

Also, The content was overlapping on each other. So, I made changes in this section as well. 
Here are the screenshots:

Screenshot (338)
Screenshot (340)

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@Mahak008 
image
This arrow should be on the left most here it has some space from the left side fix this.

**Comment by Mahak008** [comment]
> * When the size goes below 993px the arrows disappear they should be visible.
> * When the size goes below 350px "Donate Here" heading gets wrapped and the container gets overflowed fix this also.
>   We need it responsive till atleast 250-270 px.

ok

**Comment by Dhruv031003** [comment]
@Mahak008 
Please revert the changes you made in footer. It is creating issues and it is also not assigned to you.

**Comment by Dhruv031003** [comment]
@Mahak008 
Please pull the updated code for the footer.

**Comment by Mahak008** [comment]
Ok I will do it tomorrow

**Comment by Dhruv031003** [comment]
@Mahak008 
Okay No issues.

**Comment by Dhruv031003** [comment]
@Mahak008 
image
- Below 1000px footer starts coming up.

**Comment by Dhruv031003** [comment]
Please solve the merge conflicts also.

**Comment by Mahak008** [comment]
> Please solve the merge conflicts also.

I have resolved the issues. Kindly check it out.

**Comment by Dhruv031003** [comment]
@Mahak008
image
This overflowing issue is still not fixed.

**Comment by Dhruv031003** [comment]
image
These arrows also.

**Comment by Mahak008** [comment]
I have made the changes please check it out

**Comment by Dhruv031003** [comment]
@Mahak008 
image
Align these to left side like it is in the right div.

**Comment by Mahak008** [comment]
> @Mahak008 image Align these to left side like it is in the right div.

Done

**Comment by Dhruv031003** [comment]
@Mahak008 
I am merging this PR now.

Great work, Thanks for the collaboration.
Keep contributing, Kepp growing.😇😇

**Pull request merged**
