### PR TITLE
New feature

### PR DESCRIPTION
**Pull request by Utkarsh404-crypto**

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@Utkarsh404-crypto 
Please make it a 2*2 grid and fix responsiveness.

**Comment by Utkarsh404-crypto** [comment]
@Dhruv031003 I have tried to make the website as responsive as much as I could , as there were many issues regarding the units and containers in CSS. I tried everything but I don't know why the footer doesn't show up as the way it should.
But the website looks much cleaner now. Also I have made a 2x2 grid as you suggested.

**Comment by Dhruv031003** [comment]
@Utkarsh404-crypto 
There is no need to fix responsiveness of whole page.
Revert the changes only make the section responsive where you were working leave the rest.

**Comment by Utkarsh404-crypto** [comment]
@Dhruv031003 is it necessary to revert the changes as I have made the page responsive.

**Comment by Dhruv031003** [comment]
@Utkarsh404-crypto 
Yes it is.
There are many things that are out of order due to the responsiveness fix.
So please revert the changes.

**Pull request closed without merging**
