### PR TITLE
Completed Hero Section

### PR DESCRIPTION
**Pull request by SujalSamai**
Addresses Issue #8 
- Designed and updated the hero and navbar Section according to the figma design
- Changed font by using google fonts
- Added Hover effects to button
image

### CODE REVIEW

**Comment by Dhruv031003** [comment]
@SujalSamai 
image
Can you move this part a bit to the right so that it matches the ui design

**Comment by Dhruv031003** [comment]
image
Like this and please increase the font size and font color also for the same

- It would be great if you can match the colors with te UI

**Comment by SujalSamai** [comment]
I can move it certainly to the left, but it is hard to match the colors and font exactly because in the figma design, it is not mentioned which colors and font they have used. I'll try to improve it though. Thanks

**Comment by Dhruv031003** [comment]
Okay no issues. Do what you can for now i will update you if i get the fonts styles and colors or we will merge it as it is for now

**Comment by Dhruv031003** [comment]
https://www.figma.com/file/Rx5leYNrKpx169bjG7loFi/Donaate?node-id=0%3A1
If you visit this link and select the elements on the right screen you will be able to see the colors and fonts used even.
image

**Comment by SujalSamai** [comment]
Improved the layout and changed the font styling as per the figma design.
image

**Comment by Dhruv031003** [comment]
@SujalSamai 
The texts,font sizes, colors and the big quotes are still not matching with the UI

**Comment by SujalSamai** [comment]
> @SujalSamai Font ,font sizes, colors of text and Quotes behind the poem are still not matching with the UI.

It can't be perfected as it is right from the beginning, it'll take time and with more contributions it'll get better right?
Also I didn't copied it as it is, as I thought that there was little freedom on the design choices. Sorry :(

**Comment by Dhruv031003** [comment]
@SujalSamai 
No issues with that Sujal.

See, a lot of work goes into making the UI and if the UI team doesn't agree with the changes you made we have to reject the changes.
So in your future contributions if you want to make any changes in the UI, Content etc. ask beforehand.

And since your work was very good, fonts and others can be fixed later I will be merging this PR.
I am making a new issue for fonts and other fixes if you want to fix that please revert me on that issue.

**Comment by Dhruv031003** [comment]
@SujalSamai please resolve the merge conflicts then I will merge it.

**Comment by SujalSamai** [comment]
> @SujalSamai No issues with that Sujal.
> 
> See, a lot of work goes into making the UI and if the UI team doesn't agree with the changes you made we have to reject the changes. So in your future contributions if you want to make any changes in the UI, Content etc. ask beforehand.
> 
> And since your work was very good, fonts and others can be fixed later I will be merging this PR. I am making a new issue for fonts and other fixes if you want to fix that please revert me on that issue.

Sure sir, I would make changes and fix them to make it as close as I can

**Comment by SujalSamai** [comment]
This is how it looks now. I could not find the exact font for the poetname. But I downloaded the one which looks as close as possible, let me know if you need any more changes.

image

**Comment by Dhruv031003** [comment]
@SujalSamai 
It looks Much better now.

### Tips
- While working try using [camelCase](https://www.quora.com/What-is-camel-case)(specifically lower camel case) for variables, classes, id, file-names etc. This is a globally accepted practice. 
- While coding keep in mind that the site will run on devices having different viewport sizes. Some parts of the page can be made responsive without the use of media queries. 
- Example :- 
        The inverted quotes had a fixed position. But in your code they were moving with change in viewport width.
        If you use this code it will get a fixed position and won't get affected with change in width.
[newCode.txt](https://github.com/Google-Developer-Student-Club-RJIT/Donaate/files/9771504/tips.txt)

Keep these things in mind this will make you better and efficient.
Keep growing, Keep Contibuting 😇

**Pull request merged**
